<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class CategoriesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('categories')->insert([
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 0,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 1,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 1,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 1,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 2,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 0,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 3,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 0,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 4,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 1,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 5,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 1,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 6,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 0,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 7,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 1,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 8,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 1,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 9,
                'description' => Str::title('description') . '_' . Str::random(5),
                'is_featured' => 0,
                'image' => collect(['https://images.unsplash.com/photo-1498050108023-c5249f4df085','https://images.unsplash.com/photo-1461747823400-487cf1852d7e','https://images.unsplash.com/photo-1504639725590-34d0984388bd'])->random(),
                'sort_order' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'promotional_text' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}