<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 0,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 1,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'is_featured' => 1,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 1,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 1,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'is_featured' => 0,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 2,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 1,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'is_featured' => 0,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 3,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 0,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'is_featured' => 1,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 4,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 0,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'is_featured' => 1,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 5,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 1,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'is_featured' => 0,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 6,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 1,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'is_featured' => 1,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 7,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 0,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 0,
                'is_featured' => 0,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 8,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 0,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'is_featured' => 1,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => DB::table('categories')->inRandomOrder()->value('id') ?? 1,
                'name' => Str::title('name') . '_' . Str::random(5),
                'slug' => 'slug-' . Str::lower(Str::random(6)) . '-' . 9,
                'short_description' => Str::title('short_description') . '_' . Str::random(5),
                'description' => Str::title('description') . '_' . Str::random(5),
                'sku' => 'Sample_' . Str::random(5),
                'price' => 'Sample_' . Str::random(5),
                'compare_price' => 'Sample_' . Str::random(5),
                'cost_price' => 'Sample_' . Str::random(5),
                'track_stock' => 0,
                'stock_quantity' => 'Sample_' . Str::random(5),
                'low_stock_threshold' => 'Sample_' . Str::random(5),
                'is_active' => 1,
                'is_featured' => 1,
                'sort_order' => 'Sample_' . Str::random(5),
                'meta_title' => Str::title('meta_title') . '_' . Str::random(5),
                'meta_description' => Str::title('meta_description') . '_' . Str::random(5),
                'views_count' => 'Sample_' . Str::random(5),
                'average_rating' => 'Sample_' . Str::random(5),
                'reviews_count' => 'Sample_' . Str::random(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}