/**
 * Auto-generated fields for PaymentGateway
 * Generated at: 2026-06-27 14:39:25
 */
export const PaymentGatewayFields = [
  { 
    key: "id", 
    label: "Id", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "name", 
    label: "Name", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Name",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "image", 
    label: "Image", 
    type: "file", 
    cell_type: "image",
    display_field: null,
    required: 0, 
    placeholder: "Enter Image",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "value", 
    label: "Value", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 0, 
    placeholder: "Enter Value",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "requires_receipt", 
    label: "Requires Receipt", 
    type: "checkbox", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Requires Receipt",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  { 
    key: "is_active", 
    label: "Is Active", 
    type: "checkbox", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Is Active",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  { 
    key: "created_at", 
    label: "Created At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Created At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  { 
    key: "updated_at", 
    label: "Updated At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Updated At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  }
];