/**
 * Auto-generated fields for Provider
 * Generated at: 2026-04-21
 */
export const ProviderFields = [
  {
    key: "id",
    label: "Id",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 1,
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  },
  {
    key: "image",
    label: "Image",
    type: "file",
    cell_type: "image",
    display_field: null,
    required: 0,
    placeholder: "Enter Image",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: true,
    form_show: true,
    options: null
  },
  {
    key: "name",
    label: "Name",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 1,
    placeholder: "Enter Name",
    searchable: true,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  {
    key: "email",
    label: "Email",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "Enter Email",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  {
    key: "phone",
    label: "Phone",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "Enter Phone",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  {
    key: "is_active",
    label: "Is Active",
    type: "checkbox",
    cell_type: "badge",
    display_field: null,
    required: 1,
    placeholder: "Enter Is Active",
    searchable: false,
    filterable: true,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  {
    key: "package_name",
    label: "Package",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: true,
    form_show: false,
    options: null
  },
  {
    key: "services_count",
    label: "Services",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  {
    key: "reviews_count",
    label: "Reviews",
    type: "text",
    cell_type: "text",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  {
    key: "created_at",
    label: "Created At",
    type: "date",
    cell_type: "date",
    display_field: null,
    required: 0,
    placeholder: "",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
];