/**
 * Auto-generated fields for Reviews
 * Generated at: 2026-06-18 17:14:27
 */
export const ReviewsFields = [
  { 
    key: "id", 
    label: "Id", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "product_id", 
    label: "Product Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "product.name",
    required: 0, 
    placeholder: "Enter Product Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'products',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "user_id", 
    label: "User Id", 
    type: "select", 
    cell_type: "relation",
    display_field: "user.name",
    required: 0, 
    placeholder: "Enter User Id",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: true,
    endpoint: 'users',
    relation_fields: 'id,name',
    options: { label: 'name', value: 'id' }
  },
  { 
    key: "guest_name", 
    label: "Guest Name", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 0, 
    placeholder: "Enter Guest Name",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: null
  },
  { 
    key: "rating", 
    label: "Rating", 
    type: "checkbox", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Rating",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  { 
    key: "comment", 
    label: "Comment", 
    type: "text", 
    cell_type: "text",
    display_field: null,
    required: 1, 
    placeholder: "Enter Comment",
    searchable: false,
    filterable: false,
    sortable: false,
    table_show: false,
    form_show: true,
    options: null
  },
  { 
    key: "is_approved", 
    label: "Is Approved", 
    type: "checkbox", 
    cell_type: "badge",
    display_field: null,
    required: 1, 
    placeholder: "Enter Is Approved",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: true,
    options: [{ label: 'Active', value: 1, color: 'success' }, { label: 'Inactive', value: 0, color: 'danger' }]
  },
  { 
    key: "created_at", 
    label: "Created At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Created At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: true,
    form_show: false,
    options: null
  },
  { 
    key: "updated_at", 
    label: "Updated At", 
    type: "date", 
    cell_type: "date",
    display_field: null,
    required: 0, 
    placeholder: "Enter Updated At",
    searchable: false,
    filterable: false,
    sortable: true,
    table_show: false,
    form_show: false,
    options: null
  }
];